In [2]:
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv(r"heart.csv")

In [6]:
dataset

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [8]:
dataset.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [10]:
dataset.shape

(918, 12)

In [12]:
dataset.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [20]:
X = dataset.iloc[:,0:11]
y = dataset.iloc[:,11:12]

In [22]:
y.head()

HeartDisease
0             0
1             1
2             0
3             1
4             0

In [24]:
X = X.values
y = y.values

In [26]:
X[0:10,:]

array([[40, 'M', 'ATA', 140, 289, 0, 'Normal', 172, 'N', 0.0, 'Up'],
       [49, 'F', 'NAP', 160, 180, 0, 'Normal', 156, 'N', 1.0, 'Flat'],
       [37, 'M', 'ATA', 130, 283, 0, 'ST', 98, 'N', 0.0, 'Up'],
       [48, 'F', 'ASY', 138, 214, 0, 'Normal', 108, 'Y', 1.5, 'Flat'],
       [54, 'M', 'NAP', 150, 195, 0, 'Normal', 122, 'N', 0.0, 'Up'],
       [39, 'M', 'NAP', 120, 339, 0, 'Normal', 170, 'N', 0.0, 'Up'],
       [45, 'F', 'ATA', 130, 237, 0, 'Normal', 170, 'N', 0.0, 'Up'],
       [54, 'M', 'ATA', 110, 208, 0, 'Normal', 142, 'N', 0.0, 'Up'],
       [37, 'M', 'ASY', 140, 207, 0, 'Normal', 130, 'Y', 1.5, 'Flat'],
       [48, 'F', 'ATA', 120, 284, 0, 'Normal', 120, 'N', 0.0, 'Up']],
      dtype=object)

In [23]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [24]:
X[:,1]=label.fit_transform(X[:,1])
X[:,2]=label.fit_transform(X[:,2])
X[:,6]=label.fit_transform(X[:,6])
X[:,8]=label.fit_transform(X[:,8])
X[:,10]=label.fit_transform(X[:,10])

In [27]:
X[0:10,:]

array([[40, 1, 1, 140, 289, 0, 1, 172, 0, 0.0, 2],
       [49, 0, 2, 160, 180, 0, 1, 156, 0, 1.0, 1],
       [37, 1, 1, 130, 283, 0, 2, 98, 0, 0.0, 2],
       [48, 0, 0, 138, 214, 0, 1, 108, 1, 1.5, 1],
       [54, 1, 2, 150, 195, 0, 1, 122, 0, 0.0, 2],
       [39, 1, 2, 120, 339, 0, 1, 170, 0, 0.0, 2],
       [45, 0, 1, 130, 237, 0, 1, 170, 0, 0.0, 2],
       [54, 1, 1, 110, 208, 0, 1, 142, 0, 0.0, 2],
       [37, 1, 0, 140, 207, 0, 1, 130, 1, 1.5, 1],
       [48, 0, 1, 120, 284, 0, 1, 120, 0, 0.0, 2]], dtype=object)

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [31]:
X_train

array([[42, 1, 2, ..., 0, 0.8, 0],
       [36, 1, 2, ..., 0, 0.0, 2],
       [56, 1, 0, ..., 1, 1.0, 1],
       ...,
       [60, 1, 0, ..., 1, 1.4, 2],
       [60, 1, 0, ..., 1, 0.0, 2],
       [40, 0, 0, ..., 0, 2.0, 1]], dtype=object)

In [33]:
print ('X_train Shape=', X_train.shape) # taille de la partie x_train
print ('X_test Shape=', X_test.shape) # taille de la partie x_test
print ('y_train Shape=', y_train.shape) # taille de la partie y_train
print ('y_test Shape=', y_test.shape) 

X_train Shape= (734, 11)
X_test Shape= (184, 11)
y_train Shape= (734, 1)
y_test Shape= (184, 1)


In [35]:
X_test

array([[63, 0, 1, ..., 0, 0.0, 2],
       [53, 1, 2, ..., 0, 0.0, 1],
       [65, 1, 0, ..., 0, 1.2, 1],
       ...,
       [64, 1, 0, ..., 1, 1.5, 1],
       [49, 1, 1, ..., 0, 0.6, 2],
       [64, 1, 0, ..., 1, 1.0, 1]], dtype=object)

In [37]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [39]:
X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)

In [41]:
X_train[0,:]

array([42, 1, 2, 120, 240, 1, 1, 194, 0, 0.8, 0], dtype=object)

In [43]:
X_train_sc[0,:]

array([-1.24506731,  0.54060477,  1.31674291, -0.70898547,  0.372803  ,
        1.84260945,  0.01734236,  2.28435288, -0.83846064, -0.09706109,
       -2.25746543])

In [45]:
from sklearn.neighbors import KNeighborsClassifier #utiliser le module neighbors dans la bib  sklearn
knn = KNeighborsClassifier(n_neighbors = 5)

In [47]:
knn.fit(X_train_sc,y_train)

C:\Users\Pc\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [49]:
y_pred_knn = knn.predict(X_test_sc)

In [51]:
for i in range(10):
    print(y_test[i], y_pred_knn[i])

[0] 0
[1] 1
[1] 1
[1] 1
[0] 0
[1] 0
[1] 1
[0] 0
[1] 0
[1] 1


In [53]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [55]:
print('Confusion matrix knn \n', confusion_matrix(y_test,y_pred_knn))
print('Accuracy knn', accuracy_score(y_test,y_pred_knn)) 

Confusion matrix knn 
 [[68  9]
 [19 88]]
Accuracy knn 0.8478260869565217


In [57]:
from sklearn.metrics import recall_score, precision_score
print('Recall knn', recall_score(y_test,y_pred_knn))
print('Precision knn', precision_score(y_test,y_pred_knn)) 

Recall knn 0.822429906542056
Precision knn 0.9072164948453608


In [59]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.78      0.88      0.83        77
           1       0.91      0.82      0.86       107

    accuracy                           0.85       184
   macro avg       0.84      0.85      0.85       184
weighted avg       0.85      0.85      0.85       184



In [95]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

# Define the parameters for GridSearchCV
parameters = {'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15]}

# Initialize the KNeighborsClassifier
model = KNeighborsClassifier()

# Initialize GridSearchCV with the defined model and parameters
clf = GridSearchCV(model, parameters, scoring='accuracy', cv=6)

# Fit the GridSearchCV object with the training data
# Use y_train.ravel() to ensure y_train is a 1D array
grille = clf.fit(X_train_sc, y_train.ravel())

# Output the best parameters and the corresponding score
print(grille.best_params_)
print(grille.best_score_)


{'n_neighbors': 11}
0.8596561375449819


In [97]:
y_pred_knn_o = grille.predict(X_test_sc)

In [99]:
print('Confusion matrix knn op \n', confusion_matrix(y_test,y_pred_knn_o))
print('Accuracy knn op', accuracy_score(y_test,y_pred_knn_o))
print('Recall knn op', recall_score(y_test,y_pred_knn_o))
print('Precision knn op', precision_score(y_test,y_pred_knn_o))

Confusion matrix knn op 
 [[67 10]
 [19 88]]
Accuracy knn op 0.842391304347826
Recall knn op 0.822429906542056
Precision knn op 0.8979591836734694


In [803]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

In [805]:
dt.fit(X_train_sc,y_train) 

DecisionTreeClassifier()

In [807]:
y_pred_dt = dt.predict(X_test)

In [809]:
for i in range(10): # afficher les 10 première lignes
    print(y_test[i],y_pred_dt[i])

[0] 0
[1] 0
[1] 0
[1] 0
[0] 0
[1] 0
[1] 0
[0] 0
[1] 1
[1] 1


In [811]:
print('Confusion matrix dt \n', confusion_matrix(y_test,y_pred_dt))
print('Accuracy dt', accuracy_score(y_test,y_pred_dt))
print('Recall dt', recall_score(y_test,y_pred_dt))
print('Precision dt', precision_score(y_test,y_pred_dt))

Confusion matrix dt 
 [[67 10]
 [85 22]]
Accuracy dt 0.483695652173913
Recall dt 0.205607476635514
Precision dt 0.6875


In [813]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.44      0.87      0.59        77
           1       0.69      0.21      0.32       107

    accuracy                           0.48       184
   macro avg       0.56      0.54      0.45       184
weighted avg       0.58      0.48      0.43       184



In [815]:
from sklearn.svm import SVC
linear_SVM = SVC(kernel='linear') 
linear_SVM.fit(X_train_sc,y_train)

C:\Users\Pc\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [817]:
y_predictSVM_l = linear_SVM.predict(X_test_sc) #prédiction
print(confusion_matrix(y_test,y_predictSVM_l))
print('Accuracy linear SVM {0:.3f}'.format(accuracy_score(y_test,y_predictSVM_l)))
print('Precision linear SVM {0:.3f}'.format(precision_score(y_test,y_predictSVM_l)))
print('Recall linear SVM {0:.3f}'.format(recall_score(y_test,y_predictSVM_l)))

[[66 11]
 [19 88]]
Accuracy linear SVM 0.837
Precision linear SVM 0.889
Recall linear SVM 0.822


In [819]:
dataset

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [831]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, explained_variance_score
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix

# Load the dataset
dataset = pd.read_csv(r"heart.csv")

# Define X and y
X1 = dataset.drop('Cholesterol', axis=1)  # Drop the 'Cholesterol' column from X
y1 = dataset['Cholesterol']  # Set Cholesterol as the target

In [833]:
label = LabelEncoder()
X1['Sex'] = label.fit_transform(X1['Sex'])
X1['ChestPainType'] = label.fit_transform(X1['ChestPainType'])
X1['RestingECG'] = label.fit_transform(X1['RestingECG'])
X1['ExerciseAngina'] = label.fit_transform(X1['ExerciseAngina'])
X1['ST_Slope'] = label.fit_transform(X1['ST_Slope'])

In [835]:
# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [837]:
# Initialize and train the regression model
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predict the target on the test set
y_pred = regressor.predict(X_test)

In [839]:
# Calculate different regression metrics
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

# Print regression results
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R^2 Score:", r2)
print("Mean Absolute Error (MAE):", mae)


Mean Squared Error (MSE): 0.13729077851615457
Root Mean Squared Error (RMSE): 0.3705277027647927
R^2 Score: 0.4358397138678325
Mean Absolute Error (MAE): 0.29401136313025056


C:\Users\Pc\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
